### ISSUE TITLE
Can't reply to messages

### ISSUE THREAD

**Issue by austinhuang0131** [DreamTeamMobile/botbuilder-viber#3]
Action: Send any message to the bot (The bot is supposed to reply to every message)

Result: No reply

```
2017-11-09T14:23:31.909639+00:00 app[web.1]: [36m[2017-11-09 14:23:31.908] [DEBUG] [39m[36mValidating signature 'undefined' == '8e2424a0e9f276633233d569ac17b55efca8b8389f520d65eed4b6d16ae58978'[39m
```
~~Might be~~ Is actually a problem with viber-bot-node but they don't even have a issue section. I used restify for middleware though (Since botbuilder uses restify anyways).

**Comment by alexsorokoletov** [comment]
@austinhuang0131 our bot is running in production. Is that the log you're getting with your new changes?

Did you follow all steps in the readme to configure the bot?

**Comment by austinhuang0131** [comment]
I used restify for the middleware (Since I already have restify set up and I don't think restify and express can be together, i guess)

```js
var restify = require("restify");
var server = restify.createServer();
server.post('/api/messages', connector.listen());
server.post('/viber', viberChannel.listen());
```

**Comment by austinhuang0131** [comment]
In #2 I also added Webhook options into the setup (i.e. Your library will setWebhook instead of having us to manually set it). But it still doesn't work.

**Comment by alexsorokoletov** [comment]
@austinhuang0131 do you still need help on this setup?

**Comment by austinhuang0131** [comment]
My Viber account (and my bot) is gone so I guess I can't do anything anymore

**Comment by alexsorokoletov** [comment]
Sorry to hear that...

**Comment by austinhuang0131** [comment]
I mean also Viber says Public Accounts is now for big brands/celebrities only
