### ISSUE TITLE
Webhook: Data must be a string error

### ISSUE THREAD

**Issue by thynn11** [DreamTeamMobile/botbuilder-viber#4]
Hi, 

We are using the same example as in instructions and using express app. When registering webhook, we are getting this error. Any help would be appreciated.

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hmac.Hash.update (crypto.js:74:16)
    at MessageValidator._calculateHmacFromMessage (....\node_modules\viber-bot\lib\message\message-validator.js:17:54)

**Comment by alexsorokoletov** [comment]
@thynn11 looks like viber npm is crashing. I'd be glad to help if you provide me with a repro sample.

**Comment by thynn11** [comment]
@alexsorokoletov First off, thanks for the offer to help.

We learned that the issue in on our side. We had some parsing logic that's interfering with the way it's expecting. This is non issue. 

We have other errors and added some logic to handle video and endOfConversation types.

**Comment by thynn11** [comment]
@alexsorokoletov  

We are almost getting the bot working in viber. The bot is deployed in fb and skype channels but we want to add viber as a channel.

One issue left though. Somehow, the image (attached by the user) is not recognized and it kept saying "I didn't receive a file, please try again".

A sample program to troubleshoot this "file attachment" issue.
https://github.com/thynn11/botbuilder-viber-test

Any help will be really appreciated.

Thank you.

**Comment by alexsorokoletov** [comment]
Hi @thynn11 
Source code looks good to me. Do I understand correctly that you are sending picture from viber to your bot and you can't receive it?

**Comment by thynn11** [comment]
@alexsorokoletov 

Correct. If you run the program, it just has one prompt to demonstrate the issue.

Even though a picture is attached, it's still complaining with a default message "I didn't receive a file, please try again".

I tried to change the entity syntax if type === "picture" but no luck. ViberEnabledConnector.prototype.processMessage (below)
  var rawMessage = message.toJson();
        if (rawMessage.type === 'text') {
            msg = msg.text(message.text);
        } else {
            msg = msg.text('[entity]').addEntity(rawMessage);
        }
        this.handler([msg.toMessage()]);
        

Help?

Thanks.

**Comment by alexsorokoletov** [comment]
@thynn11 indeed, pictures are not recognized.
I've been able to adjust connector to correctly understand pictures and also fixed way we're translating unrecognized messages to botbuilder.

Now, with version 0.0.3 you would need to do one slight change in your `app.js`:

From:
```
    function(session, results)
    {
        session.userData.pic = results.response;
        session.endDialog("Thank you!");                
    }	
```

To:
```
    function(session, results)
    {
        var picture = results.response[0];
        var url = picture.contentUrl;
        var type = picture.contentType;
        session.userData.pic = url;
        session.endDialog("Thank you! Picture " + type + " received " + url);                
    }	
```

Example below:


<img width="697" alt="screenshot 2018-02-15 01 07 34" src="https://user-images.githubusercontent.com/1788581/36243230-7dec1b40-11ee-11e8-8f88-9a5c18156237.png">

**Comment by thynn11** [comment]
@alexsorokoletov Thanks so much. Will try it out and keep you posted.

**Comment by alexsorokoletov** [comment]
@thynn11 let me know if I can close this issue. Thank you

**Comment by thynn11** [comment]
yes, thank you!
