### ISSUE TITLE
Documentation of sending a keyboard

### ISSUE THREAD

**Issue by wkk91193** [DreamTeamMobile/botbuilder-viber#5]
Hi!

I was looking for some documentation/example on sending a customized keyboard via botbuilder-viber.

**Comment by alexsorokoletov** [comment]
@wkk91193 should be same way as for any other channel with bot builder.
Here is a conversion code to translate botbuilder keyboard to viber keyboard.
https://github.com/DreamTeamMobile/botbuilder-viber/blob/master/viber-connector.js#L137
