### ISSUE TITLE
[Question] Creating Viber Public Accounts for not-large-brands is not possible anymore?

### ISSUE THREAD

**Issue by IuriiD** [DreamTeamMobile/botbuilder-viber#9]
Hi guys! If I correctly understand this info https://support.viber.com/customer/en/portal/articles/2836126-public-accounts-faq?b_id=3838 (last updated in Dec 2017) now creating public accounts is limited only to 

> large brands and companies, and high-profile accounts in countries where Viber operates its business solutions

Is that true? Any workarounds?
Thanks.

**Comment by alexsorokoletov** [comment]
Hi!
This question is more to the Viber team. 
Please contact Viber support and they will help. 

This project is not affiliated with Viber or Microsoft. 

Alex
